### ISSUE TITLE
Fades should be able to be interrupted

### ISSUE THREAD

**Issue by mattytrentini** [mattytrentini/led_strip#4]
The fade routine should be able to be interrupted. Specifically, if the strip is off and the switch is pushed a fade-in should begin...if the switch is pushed again before the fade is complete then the fade-in should be stopped and a fade-out should begin until the strip is off.

**Comment by HowManyOliversAreThere** [comment]
Was this resolved in the move to async logic by @gidh ? (Implemented as at 0a40d1d190d6a429d6354e67f8cd80a0a55171fb)

**Comment by gidh** [comment]
From memory, yes (it's been quite a while though!)

**Comment by HowManyOliversAreThere** [comment]
Just tested and this is resolved - OK to close!
