### ISSUE TITLE
led_strip_breadboard.fzz: Unable to find part

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [mattytrentini/led_strip#5]
Upon opening the led_strip_breadboard.fzz Fritzing file, an error pops up stating, "**Unable to find the following part:** 'Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals' **at** '/home/USER/Documents/fritzing-VERSION/fritzing-parts/core/Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals.fzp' ". Error seen on Fritzing 0.9.3b.

**Comment by mattytrentini** [comment]
Hmm, interesting - as far as I can tell that's a [standard part](https://github.com/fritzing/fritzing-parts/blob/master/core/Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals.fzp). I'm on 0.9.3b too! I'll investigate further tomorrow; if I can't work out what's going on I'll just replace that part with another...

**Comment by mattytrentini** [comment]
By the way, here's an image of the breadboard:

![led_strip_breadboard_bb](https://cloud.githubusercontent.com/assets/194201/26754232/0de8672a-48ba-11e7-8e83-922d391aa38c.png)

**Comment by HowManyOliversAreThere** [comment]
No terminal block for me - definitely seems to be referencing your local copy for some reason?

![image](https://cloud.githubusercontent.com/assets/5314862/26784379/9a3dddae-4a40-11e7-9658-ad919a2441f2.png)

**Comment by mattytrentini** [comment]
I just tried installing Fritzing on my work computer (Windows 8, whereas at home I'm on Ubuntu) and the board loaded fine, including the terminal block...hmm.

I'll try to find a moment to try to swap out to another component anyway.

**Comment by HowManyOliversAreThere** [comment]
I'm on Windows 10, although it still seems strange that it's such a specific error - oh well, happy to write this off as something on my end!
